package com.bitwiseglobal.npd_space.topic1.project_one;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RewardDataObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RewardDataObject() {
    }




}